### ISSUE TITLE
Specific styles not applied correctly in iframe

### ISSUE THREAD

**Issue by monospaced** [measuredco/puck#454]
## Issue

I have some CSS that breaks in the `Puck` iframe, whilst being fine with iframe disabled, and fine in the published page. The `font` declaration is read as invalid in the iframe, and the `font-size` and `line-height` aren't applied:

```css
:root {
  --type-scale-09: 42;
  --font-09-size: calc((var(--type-scale-09) / 16) * 1rem);

  --space-scale-vertical: 24;
  --leading-scale-06: calc(var(--space-scale-vertical) * 2);
  --font-09-line-height: calc(var(--leading-scale-06) / var(--type-scale-09));
  
    --font-family: Inter, -apple-system, BlinkMacSystemFont, Segoe UI,
    Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji,
    Segoe UI Symbol;

  --font-09: var(--font-09-size) / var(--font-09-line-height) var(--font-family);
}

@supports (font-variation-settings: normal) {
  :root {
    --font-family: InterVariable, -apple-system, BlinkMacSystemFont, Segoe UI,
      Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji,
      Segoe UI Symbol;
  }
}

.msrd .msrd-Hero-strapline {
  font: var(--font-09);
  font-weight: 800;
}
```

```html
<div class="msrd>
  <p class="msrd-Hero-strapline">We are the React and UI specialists</p>
</div>
```

![Screenshot 2024-04-19 at 10 28 11](https://github.com/measuredco/puck/assets/98794/12256328-901e-457f-8fb3-666a12ef26e8)

---

## A user-land fix

Changing the CSS to this syntax fixes the issue:

```css
.msrd .msrd-Hero-strapline {
  font: 800 var(--font-09);
 /* font-weight: 800; */
}
```

![Screenshot 2024-04-19 at 10 29 42](https://github.com/measuredco/puck/assets/98794/6cbda919-0824-4d43-b46a-04a6f910d373)

**Comment by chrisvxd** [comment]
This is an interesting one.

#431 introduced fast style loading by reusing the loaded stylesheets from the host rather than reloading them in the iframe. It does this by reading the styles using the JavaScript [styleSheets API](https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheets).

Well, it turns out that this API returns a stylesheet that is slightly different from the stylesheet you provide. Specifically, it returns _expanded_ short-hand properties in _specific_ scenarios.

I tested your failing CSS `font` example, and the styleSheets API contained invalid CSS:

```css
  .msrd .msrd-Hero-strapline {
    font-style: ;
    font-variant-caps: ;
    font-stretch: ;
    font-size: ;
    line-height: ;
    font-family: ;
    font-size-adjust: ;
    font-kerning: ;
    font-optical-sizing: ;
    font-variant-alternates: ;
    font-variant-east-asian: ;
    font-variant-ligatures: ;
    font-variant-numeric: ;
    font-variant-position: ;
    font-language-override: ;
    font-feature-settings: ;
    font-variation-settings: ;
    font-weight: 800;
    letter-spacing: var(--font-11-letter-spacing);
    margin-bottom: var(--space-vertical-05);
  }
```

With your working example, it contained valid CSS:

```css
  .msrd .msrd-Hero-strapline {
    font: var(--font-11);
    font-weight: 800;
    letter-spacing: var(--font-11-letter-spacing);
    margin-bottom: var(--space-vertical-05);
  }
```

I have no idea why this is happening, but it's consistent in Chrome, Firefox and Safari. Perhaps it's the case that the exact values defined in your CSS short-hand variable is actually invalid, but the browsers are normally forgiving?

Will continue to investigate on my end.
