### ISSUE TITLE
Adaptor-fetch - Package not found

### ISSUE THREAD

**Issue by jhcueva** [measuredco/puck#85]
I try to install ```@measured/puck-adaptor-fetch``` in order to implement an adaptor-fetch 
https://github.com/measuredco/puck/blob/b5de28653759bdd29f895f1f60aef83a95eb5973/packages/adaptor-fetch/README.md?plain=1#L10
When I run the command to install the package it looks like it doesn't exists:
`❯ npm i @measured/puck-adaptor-fetch
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@measured%2fpuck-adaptor-fetch - Not found
npm ERR! 404 
npm ERR! 404  '@measured/puck-adaptor-fetch@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

**Comment by chrisvxd** [comment]
D'oh, looks like it never got added to the CI: https://github.com/measuredco/puck/blob/main/.github/workflows/publish.yml#L36C1-L40C1

The adaptor API is quite simple and I'm even a bit 50/50 about publishing it because it is literally just a wrapper around `fetch` - you should be able to implement something yourself quite easily

```jsx
const myAdaptor = {
  name: "My Adaptor",
  fetchList: async () => {
    const res = await fetch("https://www.example.com/api");

    const body = await res.json();

    return body.data;
  },
};
```

Let me know how you get on with that.

**Comment by jhcueva** [comment]
Thanks for your answer.
I have implemented the following `adaptor`
```jsx
const featuredProductsAdaptor = {
  name: "Featured Products API",
  fetchList: async () => {
    const res = await getFeaturedProducts();

    if (res) {
      const formattedData = res.map((product) => ({
        id: product.id,
        name: product.name,
        imgs: product.imgs,
        pvp: product.pvp,
        description: product.description,
      }));

      return formattedData;
    }
    return null;
  },
};
```
I want to use the adaptor in order to render the cards of the featured products, so I made the following component:
```jsx
export const ProductCardTest: ComponentConfig<ProductCardTest> = {
  fields: {
    products: {
      type: "external",
      adaptor: featuredProductsAdaptor,
    },
    title: { type: "text" },
  },

  render: ({ products, title }: { products: ProductTestProps[]; title: string }) => (
    <section style={{ width: "100%", height: "300px" }}>
      <h2>{title}</h2>
      {products &&
        products.length > 0 &&
        products.map((product, index) => (
          <div className={styles.container} key={index}>
            <a href="#">
              <img className={styles.product_image} src={product?.imgs[0]} alt={`${product.name} picture`} />
            </a>
            <div className={styles.information_container}>
              <a href="#">
                <h5 className={styles.product_title}>{product?.name}</h5>
              </a>

              <div className={styles.price_container}>
                <span className={styles.product_price}>${product?.pvp}</span>
                <a href="#" className={styles.button_buy}>
                  Add to cart
                </a>
              </div>
            </div>
          </div>
        ))}
    </section>
  ),
};
```
Styles
```css
.container {
  border-radius: 0.5rem;
  border-width: 1px;
  border-color: #e5e7eb;
  width: 100%;
  max-width: 24rem;
  background-color: #ffffff;
  box-shadow:
    0 1px 3px 0 rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.06);
}

.product_image {
  padding: 2rem;
  border-top-left-radius: 0.5rem;
  border-top-right-radius: 0.5rem;
}

.information_container {
  padding-left: 1.25rem;
  padding-right: 1.25rem;
  padding-bottom: 1.25rem;
}

.product_title {
  font-size: 1.25rem;
  line-height: 1.75rem;
  font-weight: 600;
  letter-spacing: -0.025em;
  color: #111827;
}

.price_container {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.product_price {
  font-size: 1.875rem;
  line-height: 2.25rem;
  font-weight: 700;
  color: #111827;
}

.button_buy {
  padding-top: 0.625rem;
  padding-bottom: 0.625rem;
  padding-left: 1.25rem;
  padding-right: 1.25rem;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 500;
  text-align: center;
  color: #ffffff;
  background-color: #1d4ed8;
}

.button_buy:hover {
  background-color: #1e40af;
}

```

And added to the `conf` of the editor
```jsx
export const conf: Config<Props, RootProps> = {
  root: {
    render: Root,
  },
  components: {
    Hero,
    Carrousel,
    Jumbotron,
    ProductCard,
    ProductCardTest,
  },
};
```
The component appears in the left bar of the editor and I can drag and drop it in the canvas but it does not render the cards with the products fetched from the API.
When dragged and dropped the component in the canvas,  in the left bar of the editor looks like I can select a product from the API
![image](https://github.com/measuredco/puck/assets/15198470/574e0d23-58b2-4572-8560-6835d68ca4bd)
![image](https://github.com/measuredco/puck/assets/15198470/711aa9c6-58d5-437f-8896-f32377375dec)
 I select one but nothing happens. What I tried to do is to render the list of cards of the featured products, if you can give me any advice I would be great.
 **Thanks for your time!**
